[package]
name = "server"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = { version = "4.3.1", features = ["openssl"] }
env_logger = { version = "0.10.0", features = ["color"] }
log = "0.4.17"
no-panic = "0.1.22"
openssl = { version = "0.10.52", features = ["v111"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
